import { useRouter } from 'next/router'
import { useState, useEffect } from 'react';
import moment from 'moment';
import Head from 'next/head'

import mainStyles from '../index.module.scss';
import HeaderCpn from "@/components/layouts/headerCpn";
import FooterCpn from "@/components/layouts/footerCpn";
import blogsApi from '@/api/blogs';
import styles from './termsOfUse.module.scss';

function TermsOfUse() {
    return (
        <>

            <div>
                <Head>
                    <title>Điều khoản sử dụng website</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
            </div>
            <div>
                <HeaderCpn></HeaderCpn>
                <div className={`${mainStyles.bodySec}`} >
                    <div className={`${styles.main} blogMainSec`}>
                        <div className={`d-flex justify-content-start`}>
                            <h1>Điều khoản sử dụng Website</h1>
                        </div>
                        <div className={`d-flex justify-content-end`}>
                            <h6>{timeCreated}</h6>
                        </div>
                        <div className={`m-3`} dangerouslySetInnerHTML={{ __html: blogContent }}>
                        </div>

                    </div>

                </div>

                <FooterCpn></FooterCpn>


            </div>
        </>
    );
}

export default TermsOfUse;